<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add documents' => 'Agregar documentos',
    'Add receivers to documents' => 'Agregar receptores a los documentos',
    'Allow others to create new issue on your profile page' => 'Permita que otros creen una nueva incidencia en su página de perfil',
    'Allow others to edit issue on your profile page' => 'Permita que otros editen la incidencia en su página de perfil',
    'Allow to added new receivers users to available documents' => 'Permitir agregar nuevos usuarios receptores a los documentos disponibles',
    'Allow to upload new documents and to add information on it' => 'Permitir subir nuevos documentos y agregar información sobre ellos',
    'Allow to view all documents and their all issues, with download files' => 'Permitir ver todos los documentos y todas sus incidencias, con archivos de descarga',
    'Allow to view all documents and their all issues, without access to files' => 'Permitir ver todos los documentos y todas sus incidencias, sin acceso a los archivos',
    'Allows the user to create issue' => 'Permite al usuario crear una incidencia.',
    'Allows the user to edit issue' => 'Permite al usuario editar la incidencia.',
    'Create issue' => 'Crear incidencia',
    'Edit issue' => 'Editar incidencia',
    'View all documents' => 'Ver todos los documentos',
    'View all documents and files' => 'Ver todos los documentos y archivos',
];
